Select * from STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES;

ALTER TABLE STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES ADD COLUMN RAND_NUMBER INTEGER;

Select distinct RAND_NUMBER FROM STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES ORDER BY RAND_NUMBER;

UPDATE STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES SET CREATEDDATE = to_date('2022-07-04')
WHERE RAND_NUMBER = 3;


Select count(*) from STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES;

Select count(*) from (SELECT DISTINCT COMPANEXTID FROM  STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES);


-- DELETE FROM  STEVE_D_RAW_DATA.SNAPSHOTS.OPPS_SNAPSHOT;

CREATE OR REPLACE TEMP TABLE TESTER_A AS Select * FROM STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES WHERE COMPANEXTID = 20;

Select * from TESTER_A;

UPDATE TESTER_A SET AMOUNT = '$525,034.23', CREATEDDATE =  to_date('2022-07-11'), MODIFIEDDATE =  to_date('2022-07-11') , 
OPPURTUNITY_NAME = 'Johns Inc.', PROJECT_NAME = 'Johns Inc.', COMPANEXTID = '101', BATCHID =  '18564385d8f84c94a46284bc0d7957d6';


INSERT INTO STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES SELECT * FROM TESTER_A;

UPDATE STEVE_D_RAW_DATA.SAMPLE_SALESFORCE_DATA.OPPORTUNITES SET AMOUNT = '$765,223.34', MODIFIEDDATE =  to_date('2022-07-11') WHERE COMPANEXTID = 20;

- insert into STEVE_D_RAW_DATA.SNAPSHOTS.OPPS_SNAPSHOT (select * from STEVE_D_RAW_DATA.SNAPSHOTS.OPPS_SNAPSHOT at(offset => -60*2));

Select * from STEVE_D_RAW_DATA.SNAPSHOTS.OPPS_SNAPSHOT;



Select * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE START_TIME >  to_date('2022-01-01') Limit 100;

Select 
USER_NAME,
date_trunc('MINUTE', "START_TIME") as query_run_ts_mins,
SUM(TOTAL_ELAPSED_TIME) as query_time
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE START_TIME >  to_date('2022-01-01') and user_name = 'STEVE_DOWLING'
GROUP BY 1,2;

SELECT 1;
Select * from STEVE_D_SANDBOX.DBT_SDOWLING.SF_QUERIES_BY_USER_BY_MINUTE order by ADDED_TO_TABLE_TS desc;
Select count(*) from STEVE_D_SANDBOX.DBT_SDOWLING.SF_QUERIES_BY_USER_BY_MINUTE;
-- 226
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE START_TIME >  to_date('2022-01-01') and user_name = 'STEVE_DOWLING' ORDER BY START_TIME DESC;







